using WorkflowsDemo.Models.AccomodationResearch;

namespace WorkflowsDemo.MockData;

internal static class Accommodations
{
    public static IReadOnlyList<Accommodation> Data { get; } =
    [
        new Accommodation(
            AccomodationId: "rome-001",
            AccomodationName: "Grand Roma Palace",
            Type: "Luxury Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 350,
            Rating: 4.8,
            ReviewCount: 3241,
            City: "Rome",
            District: "Centro Storico",
            Latitude: 41.9019,
            Longitude: 12.4958,
            DistanceToCityCenterKm: 0.2,
            DistanceToAirportKm: 29.1,
            Amenities: ["Pool", "Spa", "Gym", "WiFi", "Breakfast Included", "Airport Shuttle"],
            ReviewHighlights: ["Exceptional service", "Beautiful rooftop terrace", "Prime location"],
            ReviewComplaints: ["Expensive minibar", "Busy breakfast area"],
            NearbyAttractions: ["Pantheon", "Trevi Fountain", "Piazza Navona"],
            NearbyRestaurants: ["Armando al Pantheon", "Da Francesco", "Roscioli"]
        ),

        new Accommodation(
            AccomodationId: "rome-002",
            AccomodationName: "Trastevere Garden Suites",
            Type: "Boutique Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 180,
            Rating: 4.6,
            ReviewCount: 1187,
            City: "Rome",
            District: "Trastevere",
            Latitude: 41.8885,
            Longitude: 12.4708,
            DistanceToCityCenterKm: 2.6,
            DistanceToAirportKm: 25.7,
            Amenities: ["WiFi", "Breakfast Included", "Garden", "Laundry"],
            ReviewHighlights: ["Charming atmosphere", "Great nightlife nearby", "Friendly staff"],
            ReviewComplaints: ["Occasional street noise", "Small elevators"],
            NearbyAttractions: ["Santa Maria in Trastevere", "Janiculum Hill", "Tiber Island"],
            NearbyRestaurants: ["Tonnarello", "Osteria der Belli", "Nannarella"]
        ),

        new Accommodation(
            AccomodationId: "rome-003",
            AccomodationName: "Colosseum View Apartments",
            Type: "Apartment",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 160,
            Rating: 4.7,
            ReviewCount: 842,
            City: "Rome",
            District: "Monti",
            Latitude: 41.8932,
            Longitude: 12.4942,
            DistanceToCityCenterKm: 1.3,
            DistanceToAirportKm: 28.8,
            Amenities: ["WiFi", "Kitchen", "Laundry", "Air Conditioning"],
            ReviewHighlights: ["Amazing Colosseum views", "Well-equipped kitchen", "Walkable area"],
            ReviewComplaints: ["Limited parking", "Older building"],
            NearbyAttractions: ["Colosseum", "Roman Forum", "Palatine Hill"],
            NearbyRestaurants: ["La Taverna dei Fori Imperiali", "Ai Tre Scalini", "Fatamorgana"]
        ),

        new Accommodation(
            AccomodationId: "rome-004",
            AccomodationName: "Roma Backpackers Hub",
            Type: "Hostel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 40,
            Rating: 4.2,
            ReviewCount: 4521,
            City: "Rome",
            District: "Esquilino",
            Latitude: 41.8978,
            Longitude: 12.5035,
            DistanceToCityCenterKm: 1.8,
            DistanceToAirportKm: 29.5,
            Amenities: ["WiFi", "Shared Kitchen", "Lockers", "Laundry"],
            ReviewHighlights: ["Excellent value", "Social atmosphere", "Close to Termini"],
            ReviewComplaints: ["Crowded dorms", "Shared bathroom queues"],
            NearbyAttractions: ["Basilica di Santa Maria Maggiore", "Termini Station", "Colosseum"],
            NearbyRestaurants: ["Trattoria Monti", "Mercato Centrale", "Ristorante Coreano Hana"]
        ),

        new Accommodation(
            AccomodationId: "rome-005",
            AccomodationName: "Vatican Residence Hotel",
            Type: "Mid-Range Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 130,
            Rating: 4.5,
            ReviewCount: 1693,
            City: "Rome",
            District: "Prati",
            Latitude: 41.9062,
            Longitude: 12.4583,
            DistanceToCityCenterKm: 2.2,
            DistanceToAirportKm: 28.4,
            Amenities: ["WiFi", "Breakfast Included", "Airport Shuttle"],
            ReviewHighlights: ["Quiet neighborhood", "Near Vatican", "Clean rooms"],
            ReviewComplaints: ["Basic breakfast", "Limited gym facilities"],
            NearbyAttractions: ["Vatican Museums", "St. Peter's Basilica", "Castel Sant'Angelo"],
            NearbyRestaurants: ["Pizzarium", "La Zanzara", "Il Sorpasso"]
        ),

        new Accommodation(
            AccomodationId: "rome-006",
            AccomodationName: "Aventine Family Retreat",
            Type: "Family Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 220,
            Rating: 4.7,
            ReviewCount: 987,
            City: "Rome",
            District: "Aventino",
            Latitude: 41.8826,
            Longitude: 12.4834,
            DistanceToCityCenterKm: 2.8,
            DistanceToAirportKm: 26.3,
            Amenities: ["WiFi", "Family Rooms", "Breakfast Included", "Play Area"],
            ReviewHighlights: ["Great for children", "Spacious rooms", "Peaceful area"],
            ReviewComplaints: ["Limited nightlife nearby", "Few dining options"],
            NearbyAttractions: ["Orange Garden", "Circus Maximus", "Bocca della Verità"],
            NearbyRestaurants: ["Apuleius", "Panna & Co", "Rosso"]
        ),

        new Accommodation(
            AccomodationId: "rome-007",
            AccomodationName: "Termini Business Inn",
            Type: "Business Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 110,
            Rating: 4.3,
            ReviewCount: 2234,
            City: "Rome",
            District: "Castro Pretorio",
            Latitude: 41.9027,
            Longitude: 12.5074,
            DistanceToCityCenterKm: 1.6,
            DistanceToAirportKm: 30.0,
            Amenities: ["WiFi", "Business Center", "Gym", "Laundry"],
            ReviewHighlights: ["Excellent transport links", "Fast WiFi", "Professional staff"],
            ReviewComplaints: ["Busy area", "Small rooms"],
            NearbyAttractions: ["National Roman Museum", "Termini Station", "Baths of Diocletian"],
            NearbyRestaurants: ["Mamma Angela", "Pinsere", "Rifugio Romano"]
        ),

        new Accommodation(
            AccomodationId: "rome-008",
            AccomodationName: "Spanish Steps Boutique Stay",
            Type: "Boutique Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 240,
            Rating: 4.7,
            ReviewCount: 1356,
            City: "Rome",
            District: "Campo Marzio",
            Latitude: 41.9057,
            Longitude: 12.4823,
            DistanceToCityCenterKm: 0.9,
            DistanceToAirportKm: 29.3,
            Amenities: ["WiFi", "Breakfast Included", "Concierge"],
            ReviewHighlights: ["Elegant decor", "Luxury shopping nearby", "Excellent location"],
            ReviewComplaints: ["Small bathrooms", "Premium pricing"],
            NearbyAttractions: ["Spanish Steps", "Via Condotti", "Trevi Fountain"],
            NearbyRestaurants: ["Ginger Sapori", "Life Ristorante", "Ad Hoc"]
        ),

        new Accommodation(
            AccomodationId: "rome-009",
            AccomodationName: "Testaccio Urban Loft",
            Type: "Apartment",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 100,
            Rating: 4.4,
            ReviewCount: 634,
            City: "Rome",
            District: "Testaccio",
            Latitude: 41.8768,
            Longitude: 12.4767,
            DistanceToCityCenterKm: 3.4,
            DistanceToAirportKm: 25.4,
            Amenities: ["WiFi", "Kitchen", "Laundry"],
            ReviewHighlights: ["Authentic local neighborhood", "Great food scene", "Good value"],
            ReviewComplaints: ["Farther from major attractions", "Limited parking"],
            NearbyAttractions: ["Pyramid of Cestius", "Testaccio Market", "Monte Testaccio"],
            NearbyRestaurants: ["Felice a Testaccio", "Flavio al Velavevodetto", "Masto"]
        ),

        new Accommodation(
            AccomodationId: "rome-010",
            AccomodationName: "Parioli Executive Suites",
            Type: "Luxury Apartment Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 260,
            Rating: 4.6,
            ReviewCount: 721,
            City: "Rome",
            District: "Parioli",
            Latitude: 41.9251,
            Longitude: 12.4937,
            DistanceToCityCenterKm: 3.1,
            DistanceToAirportKm: 33.2,
            Amenities: ["WiFi", "Kitchen", "Gym", "Parking"],
            ReviewHighlights: ["Quiet upscale area", "Large suites", "Excellent facilities"],
            ReviewComplaints: ["Less walkable to attractions", "Higher prices"],
            NearbyAttractions: ["Villa Borghese", "MAXXI Museum", "Auditorium Parco della Musica"],
            NearbyRestaurants: ["Ai Piani", "Taverna Rossini", "Boccaccio"]
        ),

        new Accommodation(
            AccomodationId: "rome-011",
            AccomodationName: "San Giovanni Comfort Hotel",
            Type: "Budget Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 90,
            Rating: 4.1,
            ReviewCount: 1532,
            City: "Rome",
            District: "San Giovanni",
            Latitude: 41.8859,
            Longitude: 12.5068,
            DistanceToCityCenterKm: 2.9,
            DistanceToAirportKm: 27.8,
            Amenities: ["WiFi", "Breakfast Included"],
            ReviewHighlights: ["Affordable", "Good metro access", "Friendly staff"],
            ReviewComplaints: ["Dated interiors", "Thin walls"],
            NearbyAttractions: ["Basilica di San Giovanni", "Scala Santa", "Parco della Caffarella"],
            NearbyRestaurants: ["Pompi", "Osteria del Cavaliere", "La Carbonara"]
        ),

        new Accommodation(
            AccomodationId: "rome-012",
            AccomodationName: "Borghese Park Grand Hotel",
            Type: "Luxury Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 320,
            Rating: 4.8,
            ReviewCount: 1944,
            City: "Rome",
            District: "Pinciano",
            Latitude: 41.9142,
            Longitude: 12.4911,
            DistanceToCityCenterKm: 1.9,
            DistanceToAirportKm: 31.5,
            Amenities: ["Pool", "Spa", "Gym", "WiFi", "Breakfast Included"],
            ReviewHighlights: ["Beautiful gardens", "Outstanding breakfast", "Luxury experience"],
            ReviewComplaints: ["High restaurant prices", "Pool can be crowded"],
            NearbyAttractions: ["Villa Borghese", "Galleria Borghese", "Piazza del Popolo"],
            NearbyRestaurants: ["Il Margutta", "Adelaide", "Babette"]
        ),

        new Accommodation(
            AccomodationId: "rome-013",
            AccomodationName: "Campo de Fiori Guesthouse",
            Type: "Guesthouse",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 120,
            Rating: 4.5,
            ReviewCount: 1108,
            City: "Rome",
            District: "Regola",
            Latitude: 41.8953,
            Longitude: 12.4729,
            DistanceToCityCenterKm: 0.8,
            DistanceToAirportKm: 27.2,
            Amenities: ["WiFi", "Air Conditioning"],
            ReviewHighlights: ["Fantastic market nearby", "Walkable location", "Helpful hosts"],
            ReviewComplaints: ["No elevator", "Nighttime noise"],
            NearbyAttractions: ["Campo de Fiori", "Piazza Navona", "Pantheon"],
            NearbyRestaurants: ["Forno Campo de Fiori", "Ditirambo", "Roscioli"]
        ),

        new Accommodation(
            AccomodationId: "rome-014",
            AccomodationName: "EUR Modern Residence",
            Type: "Apartment Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 140,
            Rating: 4.4,
            ReviewCount: 912,
            City: "Rome",
            District: "EUR",
            Latitude: 41.8309,
            Longitude: 12.4656,
            DistanceToCityCenterKm: 8.5,
            DistanceToAirportKm: 20.4,
            Amenities: ["WiFi", "Kitchen", "Gym", "Parking"],
            ReviewHighlights: ["Modern facilities", "Convenient for business travelers", "Quiet area"],
            ReviewComplaints: ["Far from historic center", "Limited tourist atmosphere"],
            NearbyAttractions: ["Palazzo della Civiltà Italiana", "EUR Lake", "Museum of Roman Civilization"],
            NearbyRestaurants: ["Geco", "La Cannoleria Siciliana", "Marilyn Cafe"]
        ),

        new Accommodation(
            AccomodationId: "rome-015",
            AccomodationName: "Monti Artisan Hotel",
            Type: "Boutique Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 190,
            Rating: 4.6,
            ReviewCount: 1488,
            City: "Rome",
            District: "Monti",
            Latitude: 41.8958,
            Longitude: 12.4928,
            DistanceToCityCenterKm: 1.1,
            DistanceToAirportKm: 28.6,
            Amenities: ["WiFi", "Breakfast Included", "Rooftop Terrace"],
            ReviewHighlights: ["Trendy neighborhood", "Stylish rooms", "Excellent rooftop views"],
            ReviewComplaints: ["Limited room storage", "Popular and often fully booked"],
            NearbyAttractions: ["Colosseum", "Roman Forum", "Basilica di Santa Maria Maggiore"],
            NearbyRestaurants: ["Ai Tre Scalini", "Broccoletti", "Cuoco & Camicia"]
        ),

        new Accommodation(
            AccomodationId: "rome-016",
            AccomodationName: "Navona Heritage Suites",
            Type: "Boutique Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 210,
            Rating: 4.7,
            ReviewCount: 1284,
            City: "Rome",
            District: "Parione",
            Latitude: 41.8992,
            Longitude: 12.4735,
            DistanceToCityCenterKm: 0.6,
            DistanceToAirportKm: 28.4,
            Amenities: ["WiFi", "Breakfast Included", "Concierge", "Airport Shuttle"],
            ReviewHighlights: ["Historic atmosphere", "Excellent service", "Perfect location"],
            ReviewComplaints: ["Rooms vary in size", "Busy streets nearby"],
            NearbyAttractions: ["Piazza Navona", "Pantheon", "Campo de Fiori"],
            NearbyRestaurants: ["Cantina e Cucina", "Mimi e Coco", "Da Francesco"]
        ),

        new Accommodation(
            AccomodationId: "rome-017",
            AccomodationName: "Ostiense Creative Loft",
            Type: "Apartment",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 95,
            Rating: 4.3,
            ReviewCount: 512,
            City: "Rome",
            District: "Ostiense",
            Latitude: 41.8698,
            Longitude: 12.4815,
            DistanceToCityCenterKm: 4.2,
            DistanceToAirportKm: 24.7,
            Amenities: ["WiFi", "Kitchen", "Laundry", "Pet Friendly"],
            ReviewHighlights: ["Modern design", "Great local food", "Good metro access"],
            ReviewComplaints: ["Far from major landmarks", "Limited natural light"],
            NearbyAttractions: ["Centrale Montemartini", "Pyramid of Cestius", "Eataly Roma"],
            NearbyRestaurants: ["Porto Fluviale", "Osteria Fernanda", "Romeow Cat Bistro"]
        ),

        new Accommodation(
            AccomodationId: "rome-018",
            AccomodationName: "Villa Pamphili Resort",
            Type: "Resort Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 280,
            Rating: 4.8,
            ReviewCount: 1735,
            City: "Rome",
            District: "Monteverde",
            Latitude: 41.8732,
            Longitude: 12.4384,
            DistanceToCityCenterKm: 5.1,
            DistanceToAirportKm: 23.1,
            Amenities: ["Pool", "Spa", "Gym", "WiFi", "Parking"],
            ReviewHighlights: ["Resort-like atmosphere", "Beautiful grounds", "Relaxing stay"],
            ReviewComplaints: ["Requires transportation", "Limited nightlife nearby"],
            NearbyAttractions: ["Villa Doria Pamphili", "Janiculum Hill", "Trastevere"],
            NearbyRestaurants: ["L'Osteria di Monteverde", "Antica Schiacciata Romana", "Mucca Pazza"]
        ),

        new Accommodation(
            AccomodationId: "rome-019",
            AccomodationName: "Trevi Corner Inn",
            Type: "Guesthouse",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 125,
            Rating: 4.5,
            ReviewCount: 962,
            City: "Rome",
            District: "Trevi",
            Latitude: 41.9006,
            Longitude: 12.4832,
            DistanceToCityCenterKm: 0.4,
            DistanceToAirportKm: 29.2,
            Amenities: ["WiFi", "Air Conditioning", "Breakfast Included"],
            ReviewHighlights: ["Steps from Trevi Fountain", "Comfortable beds", "Great value"],
            ReviewComplaints: ["Crowded area", "Small reception"],
            NearbyAttractions: ["Trevi Fountain", "Quirinal Palace", "Pantheon"],
            NearbyRestaurants: ["Piccolo Buco", "Pane e Salame", "Il Chianti"]
        ),

        new Accommodation(
            AccomodationId: "rome-020",
            AccomodationName: "Flaminio Design Hotel",
            Type: "Design Hotel",
            TotalStayPriceAllTripMembersUsd: 0,
            NightlyPriceUsd: 170,
            Rating: 4.4,
            ReviewCount: 1041,
            City: "Rome",
            District: "Flaminio",
            Latitude: 41.9263,
            Longitude: 12.4704,
            DistanceToCityCenterKm: 3.0,
            DistanceToAirportKm: 32.7,
            Amenities: ["WiFi", "Gym", "Breakfast Included"],
            ReviewHighlights: ["Contemporary interiors", "Close to museums", "Quiet neighborhood"],
            ReviewComplaints: ["Limited room service", "Longer commute to center"],
            NearbyAttractions: ["MAXXI Museum", "Auditorium Parco della Musica", "Villa Borghese"],
            NearbyRestaurants: ["Metamorfosi", "Apoteca", "La Pariolina"]
        ),
    ];
}