using WorkflowsDemo.Models;
using WorkflowsDemo.Models.AttractionsResearch;

namespace WorkflowsDemo.MockData;

internal static class Attractions
{
    public static IReadOnlyList<Attraction> Data { get; } =
    [
        new Attraction(
            AttractionId: "rome-attraction-001",
            AttractionName: "Pantheon",
            Category: "Historical",
            Description: "Ancient Roman temple turned church, famous for its massive dome, central oculus, marble interior, and remarkably preserved classical architecture.",
            Tags: ["indoor", "historical", "architecture", "family-friendly", "wheelchair-accessible", "iconic"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 5,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.0,
            City: "Rome",
            District: "Centro Storico",
            Latitude: 41.8986,
            Longitude: 12.4769,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(9, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Tuesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 0, 0), new TimeSpan(18, 0, 0))
            ],
            Rating: 4.8,
            ReviewCount: 145230
        ),

        new Attraction(
            AttractionId: "rome-attraction-002",
            AttractionName: "Trevi Fountain",
            Category: "Historical",
            Description: "Rome's most famous Baroque fountain, known for its theatrical sculptures, turquoise water, and the tradition of tossing a coin for a return to Rome.",
            Tags: ["outdoor", "romantic", "free", "photogenic", "iconic", "crowded"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.5,
            City: "Rome",
            District: "Trevi",
            Latitude: 41.9009,
            Longitude: 12.4833,
            OpeningHours: [
                new OpeningHours("Monday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Tuesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Wednesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Thursday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Friday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Saturday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Sunday", TimeSpan.Zero, new TimeSpan(23, 59, 0))
            ],
            Rating: 4.8,
            ReviewCount: 394800
        ),

        new Attraction(
            AttractionId: "rome-attraction-003",
            AttractionName: "Piazza Navona",
            Category: "Historical",
            Description: "Elegant public square built over an ancient stadium, lined with cafés, artists, churches, and Bernini's famous Fountain of the Four Rivers.",
            Tags: ["outdoor", "free", "romantic", "food-nearby", "architecture", "family-friendly"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.0,
            City: "Rome",
            District: "Centro Storico",
            Latitude: 41.8992,
            Longitude: 12.4731,
            OpeningHours: [
                new OpeningHours("Monday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Tuesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Wednesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Thursday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Friday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Saturday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Sunday", TimeSpan.Zero, new TimeSpan(23, 59, 0))
            ],
            Rating: 4.7,
            ReviewCount: 181600
        ),

        new Attraction(
            AttractionId: "rome-attraction-004",
            AttractionName: "Santa Maria in Trastevere",
            Category: "Religious",
            Description: "One of Rome's oldest churches, admired for its golden mosaics, peaceful nave, and atmospheric location in the heart of Trastevere.",
            Tags: ["indoor", "historical", "religious", "free", "architecture", "quiet"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.75,
            City: "Rome",
            District: "Trastevere",
            Latitude: 41.8894,
            Longitude: 12.4697,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(7, 30, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Tuesday", new TimeSpan(7, 30, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(7, 30, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(7, 30, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(7, 30, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(7, 30, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(8, 0, 0), new TimeSpan(21, 0, 0))
            ],
            Rating: 4.7,
            ReviewCount: 8720
        ),

        new Attraction(
            AttractionId: "rome-attraction-005",
            AttractionName: "Janiculum Hill",
            Category: "Viewpoint",
            Description: "Scenic hill above Trastevere offering sweeping views across Rome, leafy paths, monuments, and one of the city's best sunset spots.",
            Tags: ["outdoor", "free", "romantic", "panoramic-view", "walking", "sunset"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.5,
            City: "Rome",
            District: "Trastevere",
            Latitude: 41.8919,
            Longitude: 12.4618,
            OpeningHours: [
                new OpeningHours("Monday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Tuesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Wednesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Thursday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Friday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Saturday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Sunday", TimeSpan.Zero, new TimeSpan(23, 59, 0))
            ],
            Rating: 4.7,
            ReviewCount: 19600
        ),

        new Attraction(
            AttractionId: "rome-attraction-006",
            AttractionName: "Tiber Island",
            Category: "Historical",
            Description: "Small island in the Tiber River connected by ancient bridges, known for its legends, river views, summer events, and relaxed walking routes.",
            Tags: ["outdoor", "free", "historical", "walking", "riverfront", "family-friendly"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.75,
            City: "Rome",
            District: "Ripa",
            Latitude: 41.8905,
            Longitude: 12.4773,
            OpeningHours: [
                new OpeningHours("Monday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Tuesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Wednesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Thursday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Friday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Saturday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Sunday", TimeSpan.Zero, new TimeSpan(23, 59, 0))
            ],
            Rating: 4.5,
            ReviewCount: 5800
        ),

        new Attraction(
            AttractionId: "rome-attraction-007",
            AttractionName: "Colosseum",
            Category: "Historical",
            Description: "The iconic ancient amphitheater of Rome, once used for gladiator contests and public spectacles, now one of the world's most visited monuments.",
            Tags: ["outdoor", "historical", "iconic", "guided-tours", "family-friendly", "photogenic"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 20,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 2.0,
            City: "Rome",
            District: "Celio",
            Latitude: 41.8902,
            Longitude: 12.4922,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Tuesday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Wednesday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Thursday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Friday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Saturday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Sunday", new TimeSpan(8, 30, 0), new TimeSpan(19, 15, 0))
            ],
            Rating: 4.7,
            ReviewCount: 420500
        ),

        new Attraction(
            AttractionId: "rome-attraction-008",
            AttractionName: "Roman Forum",
            Category: "Historical",
            Description: "Ancient civic heart of Rome, filled with temples, basilicas, triumphal arches, and ruins that reveal the political and social life of the empire.",
            Tags: ["outdoor", "historical", "archaeology", "walking", "guided-tours", "sun-exposed"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 20,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 2.0,
            City: "Rome",
            District: "Campitelli",
            Latitude: 41.8925,
            Longitude: 12.4853,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Tuesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0))
            ],
            Rating: 4.7,
            ReviewCount: 129400
        ),

        new Attraction(
            AttractionId: "rome-attraction-009",
            AttractionName: "Palatine Hill",
            Category: "Historical",
            Description: "Legendary hill associated with Rome's founding, featuring imperial palace ruins, gardens, archaeological remains, and excellent views over the Forum.",
            Tags: ["outdoor", "historical", "archaeology", "panoramic-view", "walking", "quiet"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 20,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.5,
            City: "Rome",
            District: "Campitelli",
            Latitude: 41.8894,
            Longitude: 12.4881,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Tuesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 0, 0), new TimeSpan(19, 15, 0))
            ],
            Rating: 4.7,
            ReviewCount: 74800
        ),

        new Attraction(
            AttractionId: "rome-attraction-010",
            AttractionName: "Basilica di Santa Maria Maggiore",
            Category: "Religious",
            Description: "Major papal basilica known for its ornate chapels, glittering mosaics, coffered ceiling, and grand blend of early Christian and Baroque design.",
            Tags: ["indoor", "religious", "historical", "architecture", "free", "wheelchair-accessible"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.0,
            City: "Rome",
            District: "Esquilino",
            Latitude: 41.8975,
            Longitude: 12.4986,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0)),
                new OpeningHours("Tuesday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0)),
                new OpeningHours("Wednesday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0)),
                new OpeningHours("Thursday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0)),
                new OpeningHours("Friday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0)),
                new OpeningHours("Saturday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0)),
                new OpeningHours("Sunday", new TimeSpan(7, 0, 0), new TimeSpan(18, 45, 0))
            ],
            Rating: 4.8,
            ReviewCount: 36100
        ),

        new Attraction(
            AttractionId: "rome-attraction-011",
            AttractionName: "Termini Station",
            Category: "Transport Hub",
            Description: "Rome's main railway station and transit hub, useful for regional trains, airport connections, metro access, shopping, and quick food options.",
            Tags: ["indoor", "transport", "shopping", "food-nearby", "wheelchair-accessible", "practical"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.5,
            City: "Rome",
            District: "Esquilino",
            Latitude: 41.9010,
            Longitude: 12.5019,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0)),
                new OpeningHours("Tuesday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(4, 30, 0), new TimeSpan(1, 0, 0))
            ],
            Rating: 4.0,
            ReviewCount: 103500
        ),

        new Attraction(
            AttractionId: "rome-attraction-012",
            AttractionName: "Vatican Museums",
            Category: "Museum",
            Description: "Vast museum complex containing papal collections, classical sculptures, Renaissance masterpieces, the Raphael Rooms, and the Sistine Chapel.",
            Tags: ["indoor", "museum", "art", "historical", "guided-tours", "wheelchair-accessible"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 22,
            PricePerChildUsd: 13,
            MinimumAge: 0,
            AverageDurationHours: 3.5,
            City: "Rome",
            District: "Vaticano",
            Latitude: 41.9065,
            Longitude: 12.4536,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(8, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Tuesday", new TimeSpan(8, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(8, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(8, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(8, 0, 0), new TimeSpan(20, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(8, 0, 0), new TimeSpan(20, 0, 0))
            ],
            Rating: 4.6,
            ReviewCount: 186700
        ),

        new Attraction(
            AttractionId: "rome-attraction-013",
            AttractionName: "St. Peter's Basilica",
            Category: "Religious",
            Description: "Monumental Renaissance basilica in Vatican City, celebrated for Michelangelo's Pietà, Bernini's baldachin, immense nave, and dome views.",
            Tags: ["indoor", "religious", "historical", "architecture", "free", "iconic"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 2.0,
            City: "Rome",
            District: "Vaticano",
            Latitude: 41.9022,
            Longitude: 12.4539,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Tuesday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(7, 0, 0), new TimeSpan(19, 0, 0))
            ],
            Rating: 4.8,
            ReviewCount: 142300
        ),

        new Attraction(
            AttractionId: "rome-attraction-014",
            AttractionName: "Castel Sant'Angelo",
            Category: "Museum",
            Description: "Cylindrical fortress and former papal refuge overlooking the Tiber, with historic rooms, military exhibits, ramparts, and rooftop city views.",
            Tags: ["indoor", "outdoor", "historical", "museum", "panoramic-view", "family-friendly"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 17,
            PricePerChildUsd: 3,
            MinimumAge: 0,
            AverageDurationHours: 1.75,
            City: "Rome",
            District: "Borgo",
            Latitude: 41.9031,
            Longitude: 12.4663,
            OpeningHours: [
                new OpeningHours("Tuesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 30, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 0, 0), new TimeSpan(19, 30, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 0, 0), new TimeSpan(19, 30, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 0, 0), new TimeSpan(19, 30, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 0, 0), new TimeSpan(19, 30, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 0, 0), new TimeSpan(19, 30, 0))
            ],
            Rating: 4.7,
            ReviewCount: 92100
        ),

        new Attraction(
            AttractionId: "rome-attraction-015",
            AttractionName: "Orange Garden",
            Category: "Park",
            Description: "Peaceful hilltop garden on the Aventine, known for orange trees, shaded paths, romantic atmosphere, and a beautiful terrace view over Rome.",
            Tags: ["outdoor", "park", "free", "romantic", "panoramic-view", "quiet"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.75,
            City: "Rome",
            District: "Aventino",
            Latitude: 41.8856,
            Longitude: 12.4801,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Tuesday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(7, 0, 0), new TimeSpan(21, 0, 0))
            ],
            Rating: 4.7,
            ReviewCount: 18400
        ),

        new Attraction(
            AttractionId: "rome-attraction-016",
            AttractionName: "Circus Maximus",
            Category: "Historical",
            Description: "Expansive ancient chariot-racing arena between the Aventine and Palatine hills, now a broad open archaeological park and event space.",
            Tags: ["outdoor", "historical", "free", "walking", "family-friendly", "archaeology"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.0,
            City: "Rome",
            District: "Ripa",
            Latitude: 41.8860,
            Longitude: 12.4857,
            OpeningHours: [
                new OpeningHours("Monday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Tuesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Wednesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Thursday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Friday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Saturday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Sunday", TimeSpan.Zero, new TimeSpan(23, 59, 0))
            ],
            Rating: 4.4,
            ReviewCount: 47800
        ),

        new Attraction(
            AttractionId: "rome-attraction-017",
            AttractionName: "Bocca della Verità",
            Category: "Historical",
            Description: "Famous ancient marble mask at the portico of Santa Maria in Cosmedin, surrounded by legends about truth-telling and a classic Roman photo stop.",
            Tags: ["outdoor", "historical", "photogenic", "family-friendly", "legendary", "quick-stop"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 2,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.5,
            City: "Rome",
            District: "Ripa",
            Latitude: 41.8882,
            Longitude: 12.4817,
            OpeningHours: [
                new OpeningHours("Monday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0)),
                new OpeningHours("Tuesday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 30, 0), new TimeSpan(17, 50, 0))
            ],
            Rating: 4.4,
            ReviewCount: 23600
        ),

        new Attraction(
            AttractionId: "rome-attraction-018",
            AttractionName: "National Roman Museum",
            Category: "Museum",
            Description: "Major archaeological museum collection spread across historic sites, featuring Roman sculptures, frescoes, mosaics, coins, and everyday ancient artifacts.",
            Tags: ["indoor", "museum", "archaeology", "historical", "rainy-day", "educational"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 12,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 2.0,
            City: "Rome",
            District: "Termini",
            Latitude: 41.9022,
            Longitude: 12.4983,
            OpeningHours: [
                new OpeningHours("Tuesday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0))
            ],
            Rating: 4.6,
            ReviewCount: 11200
        ),

        new Attraction(
            AttractionId: "rome-attraction-019",
            AttractionName: "Baths of Diocletian",
            Category: "Museum",
            Description: "Impressive remains of ancient imperial baths, now part of the National Roman Museum, with cloisters, inscriptions, sculpture, and archaeological galleries.",
            Tags: ["indoor", "outdoor", "museum", "archaeology", "historical", "quiet"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 12,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 1.5,
            City: "Rome",
            District: "Termini",
            Latitude: 41.9029,
            Longitude: 12.4989,
            OpeningHours: [
                new OpeningHours("Tuesday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Wednesday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Thursday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Friday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Saturday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0)),
                new OpeningHours("Sunday", new TimeSpan(9, 30, 0), new TimeSpan(19, 0, 0))
            ],
            Rating: 4.6,
            ReviewCount: 6700
        ),

        new Attraction(
            AttractionId: "rome-attraction-020",
            AttractionName: "Spanish Steps",
            Category: "Historical",
            Description: "Elegant monumental staircase connecting Piazza di Spagna with Trinità dei Monti, popular for people-watching, photography, and nearby luxury shopping.",
            Tags: ["outdoor", "free", "romantic", "photogenic", "shopping-nearby", "iconic"],
            TotalPriceAllTripMembersUsd: 0,
            PricePerAdultUsd: 0,
            PricePerChildUsd: 0,
            MinimumAge: 0,
            AverageDurationHours: 0.75,
            City: "Rome",
            District: "Campo Marzio",
            Latitude: 41.9059,
            Longitude: 12.4823,
            OpeningHours: [
                new OpeningHours("Monday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Tuesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Wednesday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Thursday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Friday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Saturday", TimeSpan.Zero, new TimeSpan(23, 59, 0)),
                new OpeningHours("Sunday", TimeSpan.Zero, new TimeSpan(23, 59, 0))
            ],
            Rating: 4.6,
            ReviewCount: 84600
        ),
    ];
}
